# Generated by Django 4.2.5 on 2024-01-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='desc1',
            field=models.TextField(default=''),
        ),
    ]
