# Generated by Django 4.2.5 on 2024-01-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_order_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_payment',
            name='status',
        ),
        migrations.AddField(
            model_name='product_order_buy',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
