# Generated by Django 4.2.5 on 2024-01-10 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
